### ISSUE TITLE
Feature request: progress bar / value on postgres binary download

### ISSUE THREAD

**Issue by spikecodes** [theseus-rs/postgresql-embedded#122]
https://github.com/Anush008/fastembed-rs does it really well I think how they show a CLI progress bar the first time their binaries (embeddings models) are downloaded. It would be a nice small low-priority UX addition to this project to either show a similar progress bar or otherwise give developers a "download update" event allowing them to visualize the status of the binary download.

**Comment by brianheineman** [comment]
This should already be possible by using the tracing events (e.g.: https://github.com/theseus-rs/postgresql-embedded/blob/main/postgresql_archive/src/repository/github/repository.rs#L103).  I use these events in [rsql](https://github.com/theseus-rs/rsql/blob/main/rsql_core/src/configuration.rs#L277) with the [indicatif](https://crates.io/crates/indicatif) crate to report status to the user:

<img width="556" alt="image" src="https://github.com/user-attachments/assets/db36f228-5443-4294-aed5-808377725e31">

**Comment by brianheineman** [comment]
I updated the axum example to include indicatif as well #124

**Comment by spikecodes** [comment]
@brianheineman Appreciate the help. Does that mean the current tracing can be used with indicatif to log a progress bar of the download status on the postgres binary?

**Comment by brianheineman** [comment]
@spikecodes I added progress information for archive downloads (#125); these changes are available in release [0.16.1](https://github.com/theseus-rs/postgresql-embedded/releases/tag/v0.16.1).

**Comment by spikecodes** [comment]
> @spikecodes I added progress information for archive downloads (#125); these changes are available in release [0.16.1](https://github.com/theseus-rs/postgresql-embedded/releases/tag/v0.16.1).  

Awesome thanks!
