### ISSUE TITLE
[Advice][Discussion] Using postgresql_embedded for testing

### ISSUE THREAD

**Issue by manuelarte** [theseus-rs/postgresql-embedded#128]
Hi,

I am using postgres embedded for testing, right now I have something like this:

```rust
#[cfg(test)]
mod tests {
    ... // imports

    #[tokio::test]
    async fn test_one() -> Result<(), Error> {
        let database_name = "test";
        let settings = Settings {
            port: 5435,
            ..Default::default()
        };
        let postgresql = setup(database_name, settings).await?;
        {
            // rest of the test
        }
        teardown(postgresql, database_name).await?;

        Ok(())
    }

    #[tokio::test]
    async fn test_two() -> Result<(), Error> {
        let database_name = "test";
        let settings = Settings {
            port: 5436,
            ..Default::default()
        };
        let postgresql = setup(database_name, settings).await?;
        {
            // rest of the test
        }
        teardown(postgresql, database_name).await?;

        Ok(())
    }
}
```

But I am repeating the same pattern with 

```rust
let postgresql = setup(database_name, settings).await?;
...
teardown(postgresql, database_name).await?;
```

Is this the best approach? Becuase while developing the tests, sometimes I get the rate limiting when downloading the binaries, so I was wondering if it's possible to:

- Run the tests kind in a test suite (I was googling around and could not find anything like a test suite concept for rust, but I am quite new to rust also)?
- Not download the binaries if there are already present?

Thanks

**Comment by brianheineman** [comment]
Hello @manuelarte, you can likely address the issue by specifying an exact version number to use; see: https://github.com/theseus-rs/postgresql-embedded/issues/102#issuecomment-2207305748

**Comment by manuelarte** [comment]
I changed my code to use an exact version, thanks @brianheineman
