### ISSUE TITLE
Problems with xz2, seems dead, switch to liblzma

### ISSUE THREAD

**Issue by ctron** [theseus-rs/postgresql-embedded#132]
One of the recent version seems to have introduced a dependency to [`xz2`](https://crates.io/crates/xz2). However, that dependency didn't see a release in two years. However, there's a replacement: [`liblzma`](https://crates.io/crates/liblzma), which is considered a "drop in replacement".

The problem is, only one dependency may pull in a native library. So it is not possible have an application which has both `xz2` as well as `liblzma` in the dependency tree.

Unfortunately, it looks like as if `postgresql-archive` doesn't give a choice. And doesn't support opting out.

I think it would be helpful if:

* This library can switch to the newer, maintained version
* Or, at least there's an option to select which implementation should be used.

I can come up with a PR if that helps.

**Comment by brianheineman** [comment]
This fix for this was released in [0.16.3](https://github.com/theseus-rs/postgresql-embedded/releases/tag/v0.16.3)
