### ISSUE TITLE
Can't build example diesel_embedded

### ISSUE THREAD

**Issue by tylerjw** [theseus-rs/postgresql-embedded#149]
**What steps will reproduce the bug? (please provide code snippet if relevant)**

1. copy the example code out of [diesel_embedded](https://github.com/theseus-rs/postgresql-embedded/tree/main/examples/diesel_embedded)
2. fixup the Cargo.toml to build outside the workspace with current versions
```toml
[package]
name = "diesel_embedded_test"
edition = "2021"
version = "0.6.0"

[dependencies]
diesel = { version = "2.2.4", features = ["postgres", "r2d2"] }
diesel_migrations = { version = "2.2.0", features = ["postgres"] }
postgresql_embedded = { version = "0.17" }
r2d2_postgres = "0.18.1"
tokio = { version = "1.41.0", features = ["full"] }

```

4. build failures

**What happens?*
```
   Compiling postgresql_archive v0.17.2
error[E0277]: the trait bound `TracingMiddleware<DefaultSpanBackend>: reqwest_middleware::Middleware` is not satisfied
   --> /home/tweaver/.cargo/registry/src/index.crates.io-6f17d22bba15001f/postgresql_archive-0.17.2/src/repository/github/repository.rs:323:15
    |
323 |         .with(TracingMiddleware::default())
    |          ---- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `for<'a> Fn(reqwest::Request, &'a mut Extensions, reqwest_middleware::Next<'a>)` is not implemented for `TracingMiddleware<DefaultSpanBackend>`, which is required by `TracingMiddleware<DefaultSpanBackend>: reqwest_middleware::Middleware`
    |          |
    |          required by a bound introduced by this call
    |
    = help: the following other types implement trait `reqwest_middleware::Middleware`:
              GithubMiddleware
              RetryTransientMiddleware<T, R>
    = note: required for `TracingMiddleware<DefaultSpanBackend>` to implement `reqwest_middleware::Middleware`
note: required by a bound in `reqwest_middleware::ClientBuilder::with`
   --> /home/tweaver/.cargo/registry/src/index.crates.io-6f17d22bba15001f/reqwest-middleware-0.3.3/src/client.rs:51:12
    |
49  |     pub fn with<M>(self, middleware: M) -> Self
    |            ---- required by a bound in this associated function
50  |     where
51  |         M: Middleware,
    |            ^^^^^^^^^^ required by this bound in `ClientBuilder::with`

   Compiling diesel v2.2.4
For more information about this error, try `rustc --explain E0277`.
error: could not compile `postgresql_archive` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `postgresql_archive` (lib) due to 1 previous error
```

### Information about your environment

* postgresql_embedded version: whatever is in the example
* Database version: whatever is in the example
* Operating system: rehl8

**Comment by brianheineman** [comment]
Hello @tylerjw, thank you for reporting the issue.  I was able to reproduce this with version 0.17.2.  Version [0.17.3](https://github.com/theseus-rs/postgresql-embedded/releases/tag/v0.17.3) was just released and appears to address the issue.

**Comment by tylerjw** [comment]
Sweet, thank you! Odd question, I wasn't able to figure it out through your docs. Is there a way I can specify a local path for using this in an environment where I don't have access to the internet?

**Comment by brianheineman** [comment]
You might want to take a look at `Settings.installation_dir` (https://github.com/theseus-rs/postgresql-embedded/blob/main/postgresql_embedded/src/settings.rs#L42-L43). The `installation_dir` is the path prefix without the PostgreSQL version number where the installation is located.  For instance if you set the `installation_dir` to `/foo` and the version to `17.0.1`, and you manually installed PostgreSQL to `/foo/17.0.1` I would expect that it would work without an internet connection.
