### ISSUE TITLE
programmatic interface to set pg config

### ISSUE THREAD

**Issue by JimFuller-RedHat** [theseus-rs/postgresql-embedded#73]
We would like to configure postgres with startup configurations, for example

`
shared_preload_libraries = 'pg_stat_statements
`

this can be achieved today by manually editing generated postgres.conf (and restart to pick up the change)... or I guess subsequent ALTER setting config (on non postmaster pg configs) or maybe we can do this today with pg_ctl reload (which I think is already supported here) ... will research.

Probably (optionally) pass a HashMap into the function and then process around https://github.com/theseus-rs/postgresql-embedded/blob/1973b5849caaf910adaf4a99e38631e024e9d5c2/postgresql_embedded/src/postgresql.rs#L257

maybe its possible to chain .options() so we can just add '-c shared_preload_libraries='pg_stat_statements' string ... though I do not know if the current pg config builder is aware enough or if we have to munge strings direct here.

alternately we could support PG native env vars (ex. PGDATA) to control this. Maybe this already works if we start up in default without passing in any settings ... will research.

The end goal is to start a pg with custom pg configurations.

**Comment by brianheineman** [comment]
Hello @JimFuller-RedHat, thank you for the feature request.  From the description, it sounds like you are planning on spending some more time researching this.  I put together the start of something that may meet your needs; would you mind taking a look at #74 and letting me know what your thoughts are?

**Comment by JimFuller-RedHat** [comment]
addresses perfectly ... thx ... maybe next time I will raise a PR (you were very fast!).

**Comment by brianheineman** [comment]
Please feel free to submit PRs if there are any changes / improvements you would like to see in the project

**Comment by brianheineman** [comment]
The changes for #74 have been released in version [0.10.1](https://github.com/theseus-rs/postgresql-embedded/releases/tag/v0.10.1)
